image: "rust:latest"


before_script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install.sh && sudo chmod +x install.sh && ./install.sh -y
  - rustup update
  - rustup component add clippy

lint:
  script:
    - cargo clippy -- -Wclippy::all
    - cargo fmt -- --check

build:
  script:
    - cargo build
    - cargo test