language: rust

os:
  - linux
  - windows
  - osx


before_install:
  - rustup component add clippy rustfmt


install:
  - cargo clippy -- -Wclippy::all
  - cargo fmt -- --check
  - cargo test --all-features
  - cargo doc --all-features
